### ISSUE TITLE
screenshot for practice-run-1

### ISSUE THREAD

**Issue by sainad2222** [cerc-undip/picoCTF2019-writeup#3]
![Screenshot from 2019-10-15 04-18-53](https://user-images.githubusercontent.com/44405294/66814226-e1bb8e00-ef53-11e9-8080-13bc5fdd28e3.png)

**Comment by sainad2222** [comment]
#Note# 
Added this issue just to href screenshots to solution.md.You can close these anytime.

**Comment by sainad2222** [comment]
![resources](https://user-images.githubusercontent.com/44405294/66815988-f0577480-ef56-11e9-95bb-9c44dbbc9e28.png)

**Comment by fannyhasbi** [comment]
Please insert it on README and make a PR instead issue, thanks
